# Generated by Django 5.0.1 on 2024-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessplan',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='businessplan',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
