# Generated by Django 5.0.1 on 2024-01-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessplan_business_logo_businessplan_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessplan',
            old_name='descripion',
            new_name='description',
        ),
    ]
